// packages/angular/src/lib/divider/divider.component.ts
import { Component, input, computed } from '@angular/core';

type Orientation = 'horizontal' | 'vertical';

@Component({
  selector: 'ds-divider',
  standalone: true,
  template: `<hr [class]="classes()" role="separator" [attr.aria-orientation]="orientation()" />`,
  styles: [],
})
export class DsDivider {
  orientation = input<Orientation>('horizontal');
  classes = computed(() => `divider ${this.orientation()}`);
}

// packages/react/src/components/Divider/Divider.tsx
import styles from './Divider.module.scss';

type Orientation = 'horizontal' | 'vertical';

interface DividerProps extends React.HTMLAttributes<HTMLHRElement> {
  orientation?: Orientation;
}

export function Divider({
  orientation = 'horizontal',
  className,
  ...rest
}: DividerProps) {
  const cls = [styles.divider, styles[orientation], className]
    .filter(Boolean)
    .join(' ');

  return (
    <hr
      className={cls}
      role="separator"
      aria-orientation={orientation}
      {...rest}
    />
  );
}
