// packages/react/src/components/Spinner/Spinner.tsx
import styles from './Spinner.module.scss';

type Size = 'sm' | 'md' | 'lg' | 'xl';

interface SpinnerProps extends React.HTMLAttributes<HTMLDivElement> {
  size?: Size;
  label?: string;
}

export function Spinner({
  size = 'md',
  label = 'Loading',
  className,
  ...rest
}: SpinnerProps) {
  const cls = [styles.spinner, styles[size], className].filter(Boolean).join(' ');

  return <div className={cls} role="status" aria-label={label} {...rest} />;
}

// packages/angular/src/lib/spinner/spinner.component.ts
import { Component, input, computed } from '@angular/core';

type Size = 'sm' | 'md' | 'lg' | 'xl';

@Component({
  selector: 'ds-spinner',
  standalone: true,
  template: `<div [class]="classes()" role="status" [attr.aria-label]="label()"></div>`,
  styles: [],
})
export class DsSpinner {
  size = input<Size>('md');
  label = input<string>('Loading');
  classes = computed(() => `spinner ${this.size()}`);
}
