// packages/react/src/components/Button/Button.tsx
import styles from './Button.module.scss';

type Variant = 'primary' | 'secondary' | 'ghost';
type Size = 'sm' | 'md' | 'lg';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: Variant;
  size?: Size;
  fullWidth?: boolean;
}

export function Button({
  variant = 'primary',
  size = 'md',
  fullWidth,
  className,
  children,
  ...rest
}: ButtonProps) {
  const cls = [
    styles.button,
    styles[variant],
    styles[size],
    fullWidth && styles.fullWidth,
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <button className={cls} {...rest}>
      {children}
    </button>
  );
}

// packages/angular/src/lib/button/button.component.ts
import { Component, input, computed } from '@angular/core';

type Variant = 'primary' | 'secondary' | 'ghost';
type Size = 'sm' | 'md' | 'lg';

@Component({
  selector: 'ds-button',
  standalone: true,
  template: `
    <button [class]="classes()" [disabled]="disabled()">
      <ng-content />
    </button>
  `,
  styles: [],
  host: { style: 'display: inline-block' },
})
export class DsButton {
  variant = input<Variant>('primary');
  size = input<Size>('md');
  fullWidth = input<boolean>(false);
  disabled = input<boolean>(false);

  classes = computed(() => {
    const parts = ['button', this.variant(), this.size()];
    if (this.fullWidth()) parts.push('fullWidth');
    return parts.join(' ');
  });
}
