// packages/angular/src/lib/avatar/avatar.component.ts
import { Component, input, computed } from '@angular/core';

type Size = 'sm' | 'md' | 'lg' | 'xl';

@Component({
  selector: 'ds-avatar',
  standalone: true,
  template: `
    <div [class]="classes()">
      @if (src()) {
        <img class="image" [src]="src()" [alt]="alt() ?? ''" />
      } @else {
        <span>{{ initials() }}</span>
      }
    </div>
  `,
  styles: [],
})
export class DsAvatar {
  src = input<string | undefined>(undefined);
  alt = input<string | undefined>(undefined);
  initials = input<string | undefined>(undefined);
  size = input<Size>('md');

  classes = computed(() => `avatar ${this.size()}`);
}

// packages/react/src/components/Avatar/Avatar.tsx
import styles from './Avatar.module.scss';

type Size = 'sm' | 'md' | 'lg' | 'xl';

interface AvatarProps extends React.HTMLAttributes<HTMLDivElement> {
  src?: string;
  alt?: string;
  initials?: string;
  size?: Size;
}

export function Avatar({
  src,
  alt,
  initials,
  size = 'md',
  className,
  ...rest
}: AvatarProps) {
  const cls = [styles.avatar, styles[size], className].filter(Boolean).join(' ');

  return (
    <div className={cls} {...rest}>
      {src ? (
        <img className={styles.image} src={src} alt={alt ?? ''} />
      ) : (
        <span>{initials}</span>
      )}
    </div>
  );
}
