// packages/react/src/components/Surface/Surface.tsx
import type { ElementType, CSSProperties } from 'react';
import type { PolymorphicProps } from '../../types/polymorphic';
import styles from './Surface.module.scss';

type Elevation = 'sm' | 'md' | 'lg' | 'xl';
type Rounded = 'sm' | 'md' | 'lg' | 'xl' | 'full';

const elevationMap: Record<Elevation, string> = {
  sm: styles.elevationSm,
  md: styles.elevationMd,
  lg: styles.elevationLg,
  xl: styles.elevationXl,
};

const roundedMap: Record<Rounded, string> = {
  sm: styles.roundedSm,
  md: styles.roundedMd,
  lg: styles.roundedLg,
  xl: styles.roundedXl,
  full: styles.roundedFull,
};

type SurfaceOwnProps = {
  elevation?: Elevation;
  rounded?: Rounded;
  bordered?: boolean;
  padding?: string;
  className?: string;
  style?: CSSProperties;
};

export function Surface<E extends ElementType = 'div'>({
  as,
  elevation,
  rounded,
  bordered,
  padding,
  className,
  style,
  children,
  ...rest
}: PolymorphicProps<E, SurfaceOwnProps>) {
  const Component = as ?? 'div';
  const cls = [
    styles.surface,
    elevation && elevationMap[elevation],
    rounded && roundedMap[rounded],
    bordered && styles.bordered,
    className,
  ]
    .filter(Boolean)
    .join(' ');

  const mergedStyle: CSSProperties = {
    ...style,
    ...(padding ? { padding: `var(--ds-spacing-${padding})` } : {}),
  };

  return (
    <Component className={cls} style={mergedStyle} {...rest}>
      {children}
    </Component>
  );
}

// packages/angular/src/lib/surface/surface.component.ts
import { Component, input, computed } from '@angular/core';

type Elevation = 'sm' | 'md' | 'lg' | 'xl';
type Rounded = 'sm' | 'md' | 'lg' | 'xl' | 'full';

const elevationMap: Record<Elevation, string> = {
  sm: 'elevationSm',
  md: 'elevationMd',
  lg: 'elevationLg',
  xl: 'elevationXl',
};

const roundedMap: Record<Rounded, string> = {
  sm: 'roundedSm',
  md: 'roundedMd',
  lg: 'roundedLg',
  xl: 'roundedXl',
  full: 'roundedFull',
};

@Component({
  selector: 'ds-surface',
  standalone: true,
  template: `
    @switch (tag()) {
      @case ('section') {
        <section [class]="classes()" [style.padding]="paddingStyle()"><ng-content /></section>
      }
      @case ('article') {
        <article [class]="classes()" [style.padding]="paddingStyle()"><ng-content /></article>
      }
      @case ('aside') {
        <aside [class]="classes()" [style.padding]="paddingStyle()"><ng-content /></aside>
      }
      @default {
        <div [class]="classes()" [style.padding]="paddingStyle()"><ng-content /></div>
      }
    }
  `,
  styles: [],
  host: { style: 'display: contents' },
})
export class DsSurface {
  /** HTML tag to render (renamed from 'as' to avoid reserved keyword conflict) */
  tag = input<string>('div');
  elevation = input<Elevation | undefined>(undefined);
  rounded = input<Rounded | undefined>(undefined);
  bordered = input<boolean>(false);
  padding = input<string | undefined>(undefined);

  classes = computed(() => {
    const parts = ['surface'];
    const e = this.elevation();
    const r = this.rounded();
    if (e) parts.push(elevationMap[e]);
    if (r) parts.push(roundedMap[r]);
    if (this.bordered()) parts.push('bordered');
    return parts.join(' ');
  });

  paddingStyle = computed(() => {
    const p = this.padding();
    return p ? `var(--ds-spacing-${p})` : undefined;
  });
}
